id: P008082
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17442
  title: བདེ་འཇགས་དོ་དམ་ཆད་གཅོད་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    e7bf43f1989b4f568b10ff46e0852ceb:
      image_group_id: I4PD3066
      title: ''
      volume_number: 1
      total_pages: 216
ebook_metadata:
  title: བདེ་འཇགས་དོ་དམ་ཆད་གཅོད་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  sku: P008082
  cover: cover.jpg
  layers:
  - pagination
